// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPeGIA2No5Oh8KLtwv39AU3bPfIjbBqks',
    appId: '1:876439792184:web:96514810bdac8ac4e194cd',
    messagingSenderId: '876439792184',
    projectId: 'clon-netflix-1',
    authDomain: 'clon-netflix-1.firebaseapp.com',
    storageBucket: 'clon-netflix-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYHwisUuvO0GOZEM5pBSXE3dTELXA8A9o',
    appId: '1:876439792184:android:d6890d6bd75b3861e194cd',
    messagingSenderId: '876439792184',
    projectId: 'clon-netflix-1',
    storageBucket: 'clon-netflix-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBX7tngmAZWy6Hp8LGmU3rIKZ4yibiXcc',
    appId: '1:876439792184:ios:13fea1591935772fe194cd',
    messagingSenderId: '876439792184',
    projectId: 'clon-netflix-1',
    storageBucket: 'clon-netflix-1.appspot.com',
    iosBundleId: 'com.example.memesv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBX7tngmAZWy6Hp8LGmU3rIKZ4yibiXcc',
    appId: '1:876439792184:ios:13fea1591935772fe194cd',
    messagingSenderId: '876439792184',
    projectId: 'clon-netflix-1',
    storageBucket: 'clon-netflix-1.appspot.com',
    iosBundleId: 'com.example.memesv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPeGIA2No5Oh8KLtwv39AU3bPfIjbBqks',
    appId: '1:876439792184:web:5e3e2bf380f95961e194cd',
    messagingSenderId: '876439792184',
    projectId: 'clon-netflix-1',
    authDomain: 'clon-netflix-1.firebaseapp.com',
    storageBucket: 'clon-netflix-1.appspot.com',
  );

}